---
casava_path: /n/ngs/tools/casava/CASAVA-1.8.2/bin
email_list:
- jfv@stowers.org
qc_path: /n/ngs/qcdata
script_path: /solexa/bin/scripts
admin_path: /n/ngs/runs
logs_path: /n/ngs/runs/log
flowcell_path_base: /n/ngs/data
basecalls_path: Data/Intensities/BaseCalls
fastq_combine_path: all
fastq_undetermined_combine_path: undetermined
eland_combine_path: all
fastq_filter_path: filter
project_pattern: Project_*
fastq_stats_pattern: Basecall_Stats_*
eland_stats_pattern: Summary_Stats_*
email_server: localhost:25
web_dir_root: http://molbio/solexaRuns/
num_leading_dirs_to_strip: 1

